### ISSUE TITLE
Console errors occur when switching worlds right after piloting

### ISSUE THREAD

**Issue by TrollyLoki** [TrollyLoki/Movecraft#3]
**Describe the bug**
Errors when trying to switch worlds before moving within the original world

**To Reproduce**
1. Pilot ship
2. Teleport to a different world before doing anything else
3. Error occurs in console

**Expected behavior**
Ship should still be teleported to the new world

**Comment by TrollyLoki** [comment]
Similar errors seem to be caused when teleporting into unloaded chunks with entites

**Comment by eirikh1996** [comment]
Do they happen with any ship size or?

**Comment by TrollyLoki** [comment]
It seems to mostly happen based on the chunk that the ship is teleporting, larger ships take up more chunks making it happen more often, that's my theory at least

**Comment by eirikh1996** [comment]
Is it these console errors you're refering to?

```[01:51:38 ERROR]: [Movecraft] Internal - Error - Processor thread encountered an error
[01:51:38 WARN]: java.lang.IllegalStateException: Asynchronous entity track!
[01:51:38 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:82)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.World.b(World.java:1093)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1163)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1128)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
[01:51:38 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:138)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:568)
[01:51:38 WARN]:        at org.bukkit.Location.getBlock(Location.java:91)
[01:51:38 WARN]:        at net.countercraft.movecraft.async.translation.TranslationTask.execute(TranslationTask.java:161)
[01:51:38 WARN]:        at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[01:51:38 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[01:51:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[01:51:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[01:51:38 WARN]:        at java.lang.Thread.run(Unknown Source)```

**Comment by TrollyLoki** [comment]
Yes
